version: '3.3'

services:
 web:
   container_name: "lsl-flask"
   build: ./flask
   tty: true
   volumes:
     - ./app:/app
   ports:
     - "5010:5001"
   environment:
     VIRTUAL_HOST: lsl.mimizuku.dev
     LETSENCRYPT_HOST: lsl.mimizuku.dev
     LETSENCRYPT_EMAIL: whiterythronium@gmail.com
   restart: always

 mariadb:
   image: mariadb:latest
   container_name: "lsl-mariadb"
   volumes:
     - ./mariadb:/var/lib/mysql
     - ./initdb.d:/docker-entrypoint-initdb.d
   ports:
     - "3326:3306"
   environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd

 api:
   container_name: "lsl-api"
   build: ./node
   restart: unless-stopped
   volumes:
     - ./app/node:/app/node
   working_dir: /app/node
   ports:
     - "3021:3000"
   command: sh -c "npm install -g pm2 && npm install && pm2-runtime app.js --watch"

 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: "lsl-mariadb-admin"
   links:
     - mariadb
   ports:
     - 8088:80
#   depends_on:
#     - mariadb
   volumes:
     - ./phpmyadmin/sessions:/sessions

 mongodb:
  image: mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: mongoDBRoot
    MONGO_INITDB_ROOT_PASSWORD: mongoDBPasswd
  ports:
  - 27117:27017
  volumes:
  - ./mongo/db:/data/db
  - ./mongo/configdb:/data/configdb

networks:
  default:
    external:
      name: common_link
